// <auto-generated />
namespace xPlatAuction.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class postslikeparents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postslikeparents));
        
        string IMigrationMetadata.Id
        {
            get { return "201904261103599_posts-like-parents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
