// <auto-generated />
namespace xPlatAuction.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class foreignkeyconstrain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreignkeyconstrain));
        
        string IMigrationMetadata.Id
        {
            get { return "201904261140539_foreign key constrain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
